In [1]:
import pandas as pd
import numpy as np

print("Python environment is ready!")

Python environment is ready!

In [2]:
credit_path = "../data/credit_risk/credit_risk_dataset.csv"

credit_df = pd.read_csv(credit_path)

print("Credit Risk Dataset Loaded Successfully")
print("Shape:", credit_df.shape)

Credit Risk Dataset Loaded Successfully
Shape: (32581, 12)

In [3]:
credit_df.columns

Index(['person_age', 'person_income', 'person_home_ownership',
       'person_emp_length', 'loan_intent', 'loan_grade', 'loan_amnt',
       'loan_int_rate', 'loan_status', 'loan_percent_income',
       'cb_person_default_on_file', 'cb_person_cred_hist_length'],
      dtype='object')

In [4]:
credit_df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [5]:
credit_df.dtypes

person_age                      int64
person_income                   int64
person_home_ownership          object
person_emp_length             float64
loan_intent                    object
loan_grade                     object
loan_amnt                       int64
loan_int_rate                 float64
loan_status                     int64
loan_percent_income           float64
cb_person_default_on_file      object
cb_person_cred_hist_length      int64
dtype: object

In [6]:
credit_df.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [7]:
credit_df.isna().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [8]:
credit_df.duplicated().sum()

np.int64(165)

## 165 duplicate records identified

In [9]:
credit_df["loan_status"].value_counts()

loan_status
0    25473
1     7108
Name: count, dtype: int64

In [10]:
credit_df["loan_status"].value_counts(normalize=True) * 100

loan_status
0    78.183604
1    21.816396
Name: proportion, dtype: float64

In [11]:
target_percentage = (
    credit_df["loan_status"]
    .value_counts(normalize=True)
    * 100
)

target_percentage

loan_status
0    78.183604
1    21.816396
Name: proportion, dtype: float64

In [12]:
fraud_path = "../data/fraud/creditcard.csv"

fraud_df = pd.read_csv(fraud_path)

print("Fraud Dataset Loaded Successfully")
print("Shape:", fraud_df.shape)

Fraud Dataset Loaded Successfully
Shape: (284807, 31)

In [13]:
fraud_df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [14]:
fraud_df.dtypes

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class       int64
dtype: object

In [15]:
fraud_df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [16]:
fraud_df.duplicated().sum()

np.int64(1081)

In [17]:
fraud_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [18]:
fraud_df["Class"].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [19]:
fraud_df["Class"].value_counts(normalize=True)*100

Class
0    99.827251
1     0.172749
Name: proportion, dtype: float64

In [20]:
credit_df["person_emp_length"].describe()

count    31686.000000
mean         4.789686
std          4.142630
min          0.000000
25%          2.000000
50%          4.000000
75%          7.000000
max        123.000000
Name: person_emp_length, dtype: float64

In [23]:
credit_df[credit_df["person_emp_length"] > 50][
    ["person_age", "person_emp_length", "loan_status"]
]

     person_age  person_emp_length  loan_status
0            22              123.0            1
210          21              123.0            0

In [24]:
credit_df.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [25]:
credit_df[credit_df["person_emp_length"] > 100][
    ["person_age", "person_emp_length", "loan_status"]
]

     person_age  person_emp_length  loan_status
0            22              123.0            1
210          21              123.0            0

In [26]:
age_outliers = credit_df[credit_df["person_age"] > 100][
    ["person_age", "person_income", "person_emp_length", "loan_status"]
]

age_outliers

       person_age  person_income  person_emp_length  loan_status
81            144         250000                4.0            0
183           144         200000                4.0            0
575           123          80004                2.0            0
747           123          78000                7.0            0
32297         144        6000000               12.0            0

In [27]:
income_outliers = credit_df[
    credit_df["person_income"] > 1_000_000
][
    ["person_age", "person_income", "person_emp_length", "loan_amnt", "loan_status"]
]

income_outliers

       person_age  person_income  person_emp_length  loan_amnt  loan_status
17833          32        1200000                1.0      12000            0
29119          36        1200000               16.0      10000            0
29120          40        1200000                1.0      10000            0
30049          42        2039784                0.0       8450            0
31922          47        1362000                9.0       6600            0
31924          44        1440000                7.0       6400            0
32297         144        6000000               12.0       5000            0
32497          63        1782000               13.0      12025            0
32546          60        1900000                5.0       1500            0

In [28]:
categorical_columns = [
    "person_home_ownership",
    "loan_intent",
    "loan_grade",
    "cb_person_default_on_file"
]

for column in categorical_columns:
    print(f"\n{column}")
    print(credit_df[column].value_counts())

person_home_ownership
person_home_ownership
RENT        16446
MORTGAGE    13444
OWN          2584
OTHER         107
Name: count, dtype: int64

loan_intent
loan_intent
EDUCATION            6453
MEDICAL              6071
VENTURE              5719
PERSONAL             5521
DEBTCONSOLIDATION    5212
HOMEIMPROVEMENT      3605
Name: count, dtype: int64

loan_grade
loan_grade
A    10777
B    10451
C     6458
D     3626
E      964
F      241
G       64
Name: count, dtype: int64

cb_person_default_on_file
cb_person_default_on_file
N    26836
Y     5745
Name: count, dtype: int64

In [29]:
fraud_count = fraud_df["Class"].sum()
legitimate_count = (fraud_df["Class"] == 0).sum()

fraud_ratio = legitimate_count / fraud_count

print("Fraud transactions     :", fraud_count)
print("Legitimate transactions:", legitimate_count)
print("Legitimate : Fraud     :", round(fraud_ratio, 2), ": 1")

Fraud transactions     : 492
Legitimate transactions: 284315
Legitimate : Fraud     : 577.88 : 1